### ISSUE TITLE
[Bug] Unexpected popup position with slash command plugin

### ISSUE THREAD

**Issue by devrsi0n** [Saul-Mirone/milkdown#113]
**Describe the bug**
I meet some issues when I use slash command plugin with 2 more editors on a page.
1. The popup position floats upon text, that may be related to 2 more editors usage
2. There is an appreciable latency when mouse hover between list options, see attached video. I guess it related to this code: 
![image](https://user-images.githubusercontent.com/7880675/130977929-ed70cd5b-cdbe-443e-a593-309d0d2f2d67.png), can we use `:hover` instead?
3. Can we close popup when user press key `esc`? This might be an accessibility feature request.

**To Reproduce**
https://user-images.githubusercontent.com/7880675/130977704-8f7a8a04-3bb5-490a-9d04-8bfd35aa7867.mp4

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

-   OS: [e.g. iOS] mac
-   Browser [e.g. chrome, safari] chrome
-   Version [e.g. 22] 92

**Comment by Saul-Mirone** [comment]
1. The popup position display above the text is a feature, that's because milkdown detect the space under the line won't enough for the drop down list in current view port.
2. The background transition delay has been fixed, now it's 0.2s so users won't feel that delay.
3. Esc key has been added, will be released in next version, you can try it in online demo.

**Comment by devrsi0n** [comment]
@Saul-Mirone Thank you so much.
