### ISSUE TITLE
[Feature] Image / File Uploads

### ISSUE THREAD

**Issue by underdoeg** [Saul-Mirone/milkdown#125]
**Is your feature request related to a problem? Please describe.**
To use the editor in a wiki related context, it would be useful for users to upload their images directly and not having to upload them somewhere else and then paste the link. This could happen via drag and drop as well as separate browse for file button next to the url entry.

**Describe the solution you'd like**
Most markdown editors solve this by adding an image upload handler, that returns an url to the uploaded File and then automatically ads an image or Link (for files) into the markdown code.

**Describe alternatives you've considered**
Adding an upload button outside of the markdown editor and then somehow add an image with code

**Comment by Saul-Mirone** [comment]
That's an app-level feature, I think you need a prosemirror plugin to support it. It needs to handle the clipboard events, it's similar to [@milkdown/plugin-clipboard](https://github.com/Saul-Mirone/milkdown/tree/main/packages/plugin-clipboard).

This is a common feature. However I don't have enough time for now to implement it because I'm working on the diagram feature. It would be pretty cool if you can implement as a community plugin, or wait for me to have time to support it.

**Comment by underdoeg** [comment]
Thanks I'll look into it. I think ideally it should also be integrated with the /image command.

**Comment by Saul-Mirone** [comment]
Hi @underdoeg , are you working on this?

**Comment by underdoeg** [comment]
Not yet. But will need it at?one poont

**Comment by Saul-Mirone** [comment]
> Not yet. But will need it at one point

I'm starting to work on this, you can wait for my progress.

**Comment by Saul-Mirone** [comment]
This plugin has been done here: 
https://github.com/Saul-Mirone/milkdown/blob/main/packages/plugin-upload/README.md

Will be released in next version.
