### ISSUE TITLE
Can we add support of rendering some inline HTML tags?

### ISSUE THREAD

**Issue by AayushSameerShah** [Saul-Mirone/milkdown#126]
I am sorry if the requested feature is already there (please guide if it is). But the thing is, I like to give headings in this manner ↓

# Heading<br>—
Yea ↑ that little em dash is a lot useful but that is only possible with `# Heading<br>—`  and I guess milkdown is not supporting that. Of course, then it might conflict with the WYSIWYG property, but if we can, we should.

I loved the WYSIWYG style. I needed like that. Thanks for an amazing work!

**Comment by Saul-Mirone** [comment]
This feature has not been supported in milkdown,
because it's not a very common feature. If you need that, you have 3 options:

1. Just override the css of heading nodes if you want all heading nodes to have the little dash.
2. Add an [input rule](https://prosemirror.net/docs/ref/#inputrules) to make it easy to enter a `# Heading<br>-`
3. Add a custom node, just like a [custom syntax](https://milkdown.dev/#/writing-syntax-plugins) to render it.

You can pick the one fit your needs
