### ISSUE TITLE
[Feature] Markdown extended syntax like Heading IDs

### ISSUE THREAD

**Issue by DogeVenci** [Saul-Mirone/milkdown#147]
**Describe the solution you'd like**
Many Markdown processors support custom IDs for headings — some Markdown processors automatically add them. Adding custom IDs allows you to link directly to headings and modify them with CSS. To add a custom heading ID, enclose the custom ID in curly braces on the same line as the heading.

> `### My Great Heading {#custom-id}`

The HTML looks like this:

> `<h3 id="custom-id">My Great Heading</h3>`

**Additional context**
https://www.markdownguide.org/extended-syntax/#heading-ids

**Comment by Saul-Mirone** [comment]
Thanks for your suggestion.

This can be easily implemented by:
1. Add a remark plugin to support this syntax
2. Add a custom heading node to render it in prosemirror.

I don't have plan  to implement it for now in this core library, because it's not a part of markdown standard.
I think it should be a standalone community plugin,  like https://github.com/songhn233/milkdown-plugin-shiki.
Maybe you could try to implement one if you have time for this.
