### ISSUE TITLE
[Feature] Tooltip for image can provide a button for user to add custom callback function?

### ISSUE THREAD

**Issue by leon-kfd** [Saul-Mirone/milkdown#213]
It's there a way to let user add a callback function like upload local file to server then callback a link to the input box?
![image](https://user-images.githubusercontent.com/30256102/145676504-f0a37f3a-5f28-44bf-879d-4c50562f67fc.png)

**Comment by Saul-Mirone** [comment]
Why? There's already a upload plugin: https://github.com/Saul-Mirone/milkdown/blob/main/packages/plugin-upload/README.md

**Comment by leon-kfd** [comment]
Sorry, Haven't see before. OK, I get it.

**Comment by shiyiya** [comment]
Maybe this feature is needed on the mobile.

**Comment by Saul-Mirone** [comment]
I prefer to put this feature into the menu plugin, tooltip plugin has some conflict with the native tooltip on both iOS and Android.

**Comment by shiyiya** [comment]
But not everyone needs tooltip.

**Comment by Saul-Mirone** [comment]
> 

But this image input bar is part of the tooltip plugin....

**Comment by shiyiya** [comment]
I was wrong. It's menu.

**Comment by Saul-Mirone** [comment]
Plugin cannot call another plugin directly, but they share the same ctx so they can use ctx to pass messages.
I'm saying that since tooltip plugin don't have a good experience on mobile (becauseof the conflict between native tooltip). The tooltip plugin is not designed for mobile. And mobile users should use other plugins like menu plugin or someother plugins that designed for mobile.
