### ISSUE TITLE
[Bug] Android system selection menu overlaps note contextual menu

### ISSUE THREAD

**Issue by prncc** [Saul-Mirone/milkdown#322]
**Describe the bug**

When` selecting text in a Milkdown editor, both the Milkdown menu and the android system selection menu are visible. The system menu is on top of the other one.

**To Reproduce**

1. Go to https://milkdown.dev/online-demo on an Android device
2. Select any word

**Expected behavior**

Only one menu is visible, or they don't overlap.

**Screenshots**

![image](https://user-images.githubusercontent.com/1467751/151640590-e5fe7854-26e1-4ab3-a0b4-d179839f7dc1.png)

**Smartphone (please complete the following information):**

-   OS: Android 12 (up to date) on Pixel 6
-   Browser Chrome
-   Version 97.0.4692.98 (but this was the case before)

**Comment by Saul-Mirone** [comment]
It's controlled by the Android system. We don't have anything can do about it. Same with iOS.

**Comment by prncc** [comment]
Maybe the default styles can hide the Milkdown menu OOTB?

I also tried this on iPadOS. There is a built-in basic formatting system menu there (you can bold, italicize) so at least there's something there even if the Milkdown menu is gone.

I'll leave it to you to close out the bug, in case you use it for internal organization.

**Comment by Saul-Mirone** [comment]
What if you just don't enable the tooltip plugin on Mobile?

```typescript
async setup() {
  let editor = Editor.make();

  if (!isMobile) {
    editor.use(tooltip);
  }

  return editor.create();
}
```

**Comment by duhaime** [comment]
If you wanted to keep the tooltip (which is useful for adding link href values & image src values) you could apply a simple css transform to move the tooltip below the selected text, rather than above, e.g.

```
.tooltip {
    transform: translateY(6rem);
}
```

<img width="267" alt="Screen Shot 2022-01-30 at 10 56 26 AM" src="https://user-images.githubusercontent.com/4801116/151707024-418cd65e-a1e1-43d7-8ffa-012e46902964.png">

Possibly that css could eventually happen in the milkdown, querying on user agent to see if the requesting context is an Android device...

**Comment by Saul-Mirone** [comment]
I think it's make sense for us to provide an option for tooltip plugin that can let users to choose the tooltip to appear on top or bottom.

**Comment by Saul-Mirone** [comment]
> 

I think we can have a user defined position to let users customize the position.

**Comment by quank123wip** [comment]
@prncc I have make a new commit which provides a option in @milkdown/plugin-tooltip, allows user to change the tooltip's position when it loads. It helps a lot but still can't solve this because when the content is on the bottom of the editor, the tooltip's desired to be on the top of the selected content. We need more workarounds to solve this problem.

**Comment by Saul-Mirone** [comment]
Closing since we can configure the top/bottom of the tooltip.
