### ISSUE TITLE
Add markdown text highlight option

### ISSUE THREAD

**Issue by jrcacd** [Saul-Mirone/milkdown#426]
https://www.markdownguide.org/extended-syntax/#highlight

**Comment by Saul-Mirone** [comment]
I don't have a plan to do this. You can create a community plugin. It would be easy.

**Comment by panchicore** [comment]
dear Saul, would you provide some hints or high-level details on how to create it?

**Comment by Saul-Mirone** [comment]
> dear Saul, would you provide some hints or high-level starter details on how to create it?

Sure, I'm writing the new docs. Will let you know once it's completed.

**Comment by Saul-Mirone** [comment]
> 

Since our new API documents are finished, I think it's time to give it a try if you're still interested in it.

It should be a `Mark` plugin, and it will very similar to strkethrough or italic, you can find the code here:
https://github.com/Milkdown/milkdown/blob/main/packages/preset-gfm/src/mark/strike-through.ts

It's easy to implement IMO.

**Comment by adaboese** [comment]
@Saul-Mirone Would it be similar for my use case of needing to highlight a keyword?

https://github.com/orgs/Milkdown/discussions/1178

**Comment by adaboese** [comment]
I found this ProseMirror code that does what I want.

https://gist.github.com/marijnh/cee01b30b1890a5947c0

Just unsure how that translates to Milkdown.
