### ISSUE TITLE
[Bug] Mouse event cause content scroll to top after switching editable to false

### ISSUE THREAD

**Issue by z-950** [Saul-Mirone/milkdown#624]
**Describe the bug**
Mouse event cause content scroll to top after switching editable to false.

**To Reproduce**
1. Create editor like 
``` js
Editor.make()
    .config((ctx) => {
        ctx.update(editorViewOptionsCtx, (prev) => ({ ...prev, editable: getEditable }));
    })
    .use(nord).use(commonmark).create()
```
4. Set editable to false like
``` js
editable = false;
editor.action((ctx) => {
    const view = ctx.get(editorViewCtx);
    view.update(view.props);
});
```
3. Scroll down.
4. Click content.
5. Auto scroll to top.

**Expected behavior**
Content should not be scrolled.

**Milkdown version**
```
    "@milkdown/core": "^6.3.0",
    "@milkdown/preset-commonmark": "^6.3.0",
    "@milkdown/theme-nord": "^6.3.0",
```

**Desktop (please complete the following information):**
- OS: Windows10
- Browser Chrome
- Version 101.0.4951.67

**Additional context**
I found it is caused by updating menu plugin which call `editorRoot.appendChild(milkdownDOM);`.

**Comment by Saul-Mirone** [comment]
I need to rollback this change, because this change breaks two things:

1. The global menuWrapper breaks the behavior of multiple editor instances (because they're forced to share one wrapper).
2. In readonly mode, the expect behavior is that the menu wrapper dom should not be exists.

I think to keep the scroll top, you may need to record the scroll offset before switching editable, and restore it after the switch finish.

**Comment by z-950** [comment]
All right.
I think the first break things can be fixed. But the second one is hard to deal. I think that a common wrapper is better for plugin, but not menu wapper.
